language: python

matrix:
  fast_finish: true
  include:
    - { python: '3.7-dev', env: TOX_ENV=flake8 }
    - { python: '3.7-dev', env: TOX_ENV=py37-django1.11-mezzanine4.3 }
    - { python: '3.7-dev', env: TOX_ENV=py37-mezzaninemaster }
  allow_failures:
    - env: TOX_ENV=py37-mezzaninemaster

install:
  - pip install tox

script:
  - tox -e $TOX_ENV
