language: python

sudo: false

env:
    - TOX_ENV=flake8
    - TOX_ENV=py27-django1.6-drf3.1-mezzanine3.1
    - TOX_ENV=py34-django1.6-drf3.1-mezzanine3.1
    - TOX_ENV=py27-mezzaninemaster
    - TOX_ENV=py34-mezzaninemaster

matrix:
  fast_finish: true
  allow_failures:
    - env: TOX_ENV=py27-mezzaninemaster
    - env: TOX_ENV=py34-mezzaninemaster

install:
  - pip install tox

script:
    - tox -e $TOX_ENV