site_name: Mezzanine REST API
site_description: RESTful web API for Mezzanine CMS
site_author: George Cushen
site_url: http://gcushen.github.io/mezzanine-api

repo_name: 'GitHub'
repo_url: https://github.com/gcushen/mezzanine-api

copyright: 'Copyright &copy; 2015 - present <a href="https://twitter.com/GeorgeCushen">George Cushen</a>.'

theme:
  name: 'material'
  language: 'en'
  logo: img/mezzanine_api_logo.png
  palette:
    primary: 'red'
    accent: 'red'
  font:
    text: 'Roboto'
    code: 'Roboto Mono'
extra_css:
  - css/extra.css


extra:
  social:
    - type: 'github'
      link: 'https://github.com/gcushen'
    - type: 'twitter'
      link: 'https://twitter.com/GeorgeCushen'

nav:
- Mezzanine API: 'index.md'
- Authentication: 'authentication.md'
- Release Notes: 'release-notes.md'
- Client SDK: 'client.md'
- Remote CLI: 'cli.md'

markdown_extensions:
  - admonition
  - codehilite:
      guess_lang: true
  - toc:
      permalink: true

google_analytics:
  - 'UA-62992791-1'
  - 'auto'
