site_name: Mezzanine REST API
site_url: http://gcushen.github.io/mezzanine-api
site_description: RESTful web API for Mezzanine CMS
site_author: George Cushen

repo_url: https://github.com/gcushen/mezzanine-api/

markdown_extensions:
    - admonition:

copyright: Copyright &copy; 2015 <a href="https://twitter.com/GeorgeCushen">George Cushen</a>.
google_analytics: ['UA-62992791-1', 'auto']
