site_name: Mezzanine REST API
site_description: RESTful web API for Mezzanine CMS
site_author: George Cushen
site_url: http://gcushen.github.io/mezzanine-api

repo_name: 'GitHub'
repo_url: https://github.com/gcushen/mezzanine-api

copyright: 'Copyright &copy; 2016 <a href="https://twitter.com/GeorgeCushen">George Cushen</a>.'

theme: 'material'

extra:
  logo: img/mezzanine_api_logo.png
  font:
    text: 'Roboto'
    code: 'Roboto Mono'
  author:
    github: 'gcushen'
    twitter: 'GeorgeCushen'

pages:
- Mezzanine API: 'index.md'
- Authentication: 'authentication.md'
- Release Notes: 'release-notes.md'
- Client SDK: 'client.md'

markdown_extensions:
  - codehilite(css_class=code)
  - admonition

google_analytics:
  - 'UA-62992791-1'
  - 'auto'
