site_name: Mezzanine REST API
site_description: RESTful web API for Mezzanine CMS
site_author: George Cushen
site_url: http://gcushen.github.io/mezzanine-api

repo_name: 'GitHub'
repo_url: https://github.com/gcushen/mezzanine-api

copyright: 'Copyright &copy; 2017 <a href="https://twitter.com/GeorgeCushen">George Cushen</a>.'

theme: 'material'
extra_css:
  - css/extra.css

extra:
  palette:
    primary: 'red'
    accent: 'red'
  logo: img/mezzanine_api_logo.png
  font:
    text: 'Roboto'
    code: 'Roboto Mono'
  social:
    - type: 'github'
      link: 'https://github.com/gcushen'
    - type: 'twitter'
      link: 'https://twitter.com/GeorgeCushen'

pages:
- Mezzanine API: 'index.md'
- Authentication: 'authentication.md'
- Release Notes: 'release-notes.md'
- Client SDK: 'client.md'
- Remote CLI: 'cli.md'

markdown_extensions:
  - admonition

google_analytics:
  - 'UA-62992791-1'
  - 'auto'
